#**1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

NumPy, short for Numerical Python, is a foundational library in Python for scientific computing and data analysis. Its primary purpose is to provide a powerful framework for working with numerical data efficiently. Here are some of its key advantages and how it enhances Python's capabilities for numerical operations:

##Purpose of NumPy:

###Array Handling:

NumPy introduces the ndarray (n-dimensional array) object, which allows for the efficient storage and manipulation of large datasets. Unlike Python's built-in lists, NumPy arrays support multidimensional data structures.

Numerical Computation: It provides a plethora of mathematical functions to perform operations on arrays, facilitating complex computations, including linear algebra, Fourier transforms, and random number generation.

###Interoperability:

 NumPy serves as the backbone for many other scientific libraries in Python, such as SciPy, Pandas, and Matplotlib, making it essential for data analysis and visualization tasks.

##Advantages of NumPy:

###Performance:

NumPy is implemented in C and Fortran, which allows it to execute operations much faster than standard Python code, particularly for large datasets. The ability to perform element-wise operations on arrays without the need for explicit loops results in significant performance improvements.

###Convenience:

NumPy simplifies the syntax for array operations. It supports broadcasting, which automatically expands arrays of different shapes for arithmetic operations, enabling cleaner and more intuitive code.

###Comprehensive Mathematical Functions:

It provides a rich set of functions for mathematical operations, including statistics, linear algebra, and random number generation, making it a one-stop solution for many numerical problems.

###Memory Efficiency:

NumPy arrays consume less memory than Python lists, as they store data in a contiguous block of memory and support various data types, reducing overhead.

###Indexing and Slicing:

NumPy supports advanced indexing and slicing techniques, which allow users to manipulate large datasets easily without complex code.

###Community and Ecosystem:

As a widely adopted library, NumPy benefits from a large community of users and contributors. This support results in extensive documentation, tutorials, and numerous complementary libraries.

##Enhancements to Python's Numerical Capabilities:

###Speed:
NumPy's array operations are executed in compiled code, leading to execution speeds that can be orders of magnitude faster than pure Python.

###Vectorization:

It allows for vectorized operations, meaning operations can be applied to entire arrays at once instead of element by element, which not only improves speed but also leads to cleaner code.

###Data Types:

NumPy supports a variety of data types, enabling efficient storage and manipulation of different kinds of numerical data (e.g., integers, floats, complex numbers).

###Linear Algebra and Fourier Transforms:

Built-in functions for complex mathematical operations make it easier to perform tasks like matrix multiplication or spectral analysis without needing external libraries.

#**2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**

The np.mean() and np.average() functions in NumPy are both used to compute the central tendency of an array, but they have some important differences in terms of functionality and flexibility.

##np.mean():

###Purpose:

Calculates the arithmetic mean of the elements along a specified axis.

###Syntax:

np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

###Default Behavior:

Computes the mean of all elements in the array by default, without weighting.

###Parameters:

* a: Input array.
* axis: Axis or axes along which to compute the mean.
* dtype: Data type used in the calculation.
* out: Alternative output array to store the result.
* keepdims: If set to True, retains the dimensions of the input array.
##np.average():

###Purpose:

Computes the weighted average of the elements. If no weights are specified, it defaults to the arithmetic mean.
###Syntax:

np.average(a, axis=None, weights=None, returned=False)

###Default Behavior:

If no weights are provided, it behaves like np.mean(). However, you can specify weights to influence the average.

###Parameters:

* a: Input array.
* axis: Axis or axes along which to compute the average.
* weights: An array of weights associated with the values in a.
* returned: If True, returns a tuple containing the average and the sum of the weights.
##Key Differences:

###1. Weighting:

* np.mean() does not allow for any weighting of the data; it treats all values equally.
* np.average() can accept a weights parameter, allowing you to compute a weighted average where some values contribute more to the average than others.

###2. Flexibility:

* If you need to compute a simple mean of an array, np.mean() is straightforward and sufficient.

* If you require a calculation that considers the relative importance of different values, np.average() is the better choice.
Return Value:

* Both functions return the mean or average, but np.average() can also return the total of the weights when the returned parameter is set to True.

##When to Use Which:

###Use np.mean() when:

* You simply need the arithmetic mean of an array or along a specific axis without any weighting.
* You want a straightforward, easy-to-read function for calculating the mean.

###Use np.average() when:

* You need to compute a weighted average, where certain values should contribute more significantly than others.
* You want the flexibility to also obtain the total of the weights.


#Example:





In [25]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(data)

average_value = np.average(data)

weights = np.array([1, 1, 1, 1, 5])

weighted_average = np.average(data, weights=weights)

In [26]:
print(mean_value)

3.0


In [27]:
print(average_value)

3.0


In [28]:
print(weighted_average)

3.888888888888889


In this example, np.mean() and np.average() without weights yield the same result, but np.average() with weights gives a different value, illustrating its flexibility.

#**3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

Reversing a NumPy array can be done using various methods, depending on whether you're dealing with a 1D or a 2D array and which axis you want to reverse along. Here are the main techniques:

##1D Array Reversal:

For a 1D array, you can reverse the array using slicing.

#Example:

In [29]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])

reversed_1d = array_1d[::-1]

print("Original 1D array:", array_1d)
print("Reversed 1D array:", reversed_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


##2D Array Reversal:

For a 2D array, you can reverse along different axes (rows or columns) using slicing as well.

#Example:

In [31]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

reversed_2d_all = array_2d[::-1, ::-1]

reversed_2d_rows = array_2d[::-1]

reversed_2d_cols = array_2d[:, ::-1]

print("Original 2D array:\n", array_2d)
print("Reversed 2D array (all):\n", reversed_2d_all)
print("Reversed 2D array (rows):\n", reversed_2d_rows)
print("Reversed 2D array (columns):\n", reversed_2d_cols)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D array (all):
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reversed 2D array (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D array (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


#**4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance**

To determine the data type of elements in a NumPy array, you can use the .dtype attribute of the array. This attribute provides information about the data type of the array's elements.

#Example:


In [32]:
import numpy as np

int_array = np.array([1, 2, 3, 4, 5])
print("Data type of int_array:", int_array.dtype)

float_array = np.array([1.0, 2.0, 3.0])
print("Data type of float_array:", float_array.dtype)

str_array = np.array(['a', 'b', 'c'])
print("Data type of str_array:", str_array.dtype)

Data type of int_array: int64
Data type of float_array: float64
Data type of str_array: <U1


##Importance of Data Types in NumPy:

###1. Memory Management:

####Storage Size:

Different data types require different amounts of memory. For example, an int32 type uses 4 bytes, while an int64 uses 8 bytes. Using an appropriate data type helps optimize memory usage, especially when working with large datasets.

####Arrays of Objects:

If you use the generic object type (e.g., dtype=object), it may lead to inefficient memory use and slow performance due to the overhead of Python objects.

###2. Performance:

####Computational Speed:
Operations on arrays of specific, smaller data types (like float32 instead of float64) can be faster due to reduced data size and improved cache efficiency. This can significantly enhance performance in numerical computations.

####Vectorized Operations:
NumPy's performance benefits from its ability to perform operations on whole arrays at once. Specific data types allow for optimized implementations of these operations, leading to faster execution times compared to using generic Python lists.

###3. Type Safety:

Using specific data types helps prevent errors related to incompatible data types, which can lead to bugs in calculations or unexpected behavior. For example, mixing integers and floats in calculations can sometimes yield unexpected results if not handled correctly.

###4. Numerical Accuracy:

Choosing the right data type can affect the precision of calculations. For example, using float32 instead of float64 can lead to precision loss in floating-point arithmetic, which might be critical in certain applications, such as scientific computing or financial calculations.

#**5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

##Key Features of ndarrays:

###1. Homogeneous Data:

All elements in an ndarray are of the same data type, which enables NumPy to optimize performance and memory usage. This contrasts with Python lists, which can hold mixed types.

###2. Multidimensional:

Ndarrays can be one-dimensional (1D), two-dimensional (2D), or even n-dimensional. This flexibility allows users to represent complex data structures, such as matrices, tensors, and higher-dimensional data.

###3. Efficient Memory Layout:

Ndarrays store data in contiguous blocks of memory, which enhances cache performance and reduces overhead compared to Python lists, which are arrays of pointers to objects.

###4. Vectorized Operations:

NumPy allows for element-wise operations on ndarrays without the need for explicit loops. This feature enables concise and efficient computations on large datasets.

###5. Broadcasting:

Ndarrays support broadcasting, allowing operations between arrays of different shapes. This makes it easy to perform arithmetic operations without manually reshaping arrays.

###6. Comprehensive Functionality:

NumPy provides a rich set of mathematical functions and methods for ndarrays, including linear algebra, statistics, Fourier transforms, and more.

###7. Flexible Indexing:

Ndarrays offer advanced indexing and slicing capabilities, allowing users to access and manipulate specific parts of the array efficiently.

###8. Dimensionality:

The shape of an ndarray can be easily queried and modified using properties like .shape and .ndim, which helps manage and understand the structure of the data.

##Differences from Standard Python Lists:

###1. Data Type Uniformity:

####Ndarrays:

All elements must be of the same data type.

####Python Lists:

Can contain elements of varying types (e.g., integers, floats, strings).

###2.  Performance:

####Ndarrays:

Faster for numerical computations due to optimized memory layout and operations implemented in compiled code.

####Python Lists:

Slower for numerical tasks since they are more flexible but less efficient.

###3. Functionality:

####Ndarrays:

Equipped with a wide range of mathematical functions and operations that can be applied directly to the entire array.
####Python Lists:

Lack built-in support for mathematical operations; require loops or list comprehensions for similar functionality.
###4. Memory Consumption:

####Ndarrays:

More memory-efficient due to contiguous storage and homogeneous data types.
####Python Lists:

Require additional memory overhead for storing pointers to objects.

###5. Slicing and Indexing:

####Ndarrays:

Support advanced slicing and indexing, including boolean indexing and fancy indexing.
####Python Lists:

Support basic slicing but do not have the same level of indexing flexibility.

#Example:


In [33]:
import numpy as np

ndarray = np.array([1, 2, 3, 4, 5])
ndarray_squared = ndarray ** 2

py_list = [1, 2, 3, 4, 5]
list_squared = [x ** 2 for x in py_list]

print("NumPy ndarray:", ndarray_squared)
print("Python list squared:", list_squared)

NumPy ndarray: [ 1  4  9 16 25]
Python list squared: [1, 4, 9, 16, 25]


#**6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations, primarily due to their optimized design and implementation. Here are the key areas where NumPy arrays outperform Python lists:

##1. Memory Efficiency:

###Contiguous Memory Storage:

NumPy arrays store data in contiguous blocks of memory, which reduces overhead and improves cache performance. This is in contrast to Python lists, which are arrays of pointers to objects. Each element in a list requires additional memory for the pointer, leading to increased memory consumption.

###Homogeneous Data Types:

Since all elements in a NumPy array are of the same data type, the array can use a more compact memory representation. In contrast, Python lists can contain mixed data types, resulting in higher memory usage due to the overhead of storing references to different object types.

##2. Performance of Mathematical Operations:

Vectorized Operations: NumPy supports vectorized operations that allow for element-wise computations directly on entire arrays without the need for explicit loops. This is implemented in optimized C code, making operations significantly faster than looping through Python lists.

#Example:

In [38]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
result = a + b
print(result)

[6 6 6 6 6]


In contrast, doing the same with Python lists requires a loop:

In [40]:
py_list_a = [1, 2, 3, 4, 5]
py_list_b = [5, 4, 3, 2, 1]
result_list = [x + y for x, y in zip(py_list_a, py_list_b)]
print(result_list)

[6, 6, 6, 6, 6]


##3. Optimized Computational Functions:

###Built-in Mathematical Functions:

NumPy provides a rich set of optimized mathematical functions that operate directly on arrays. These functions are implemented in compiled code, which is much faster than equivalent operations performed on Python lists.

For example, using np.mean() on a large NumPy array is more efficient than calculating the mean using a loop on a list.

##4. Reduced Overhead for Large Datasets:

###Batch Processing:

NumPy arrays are designed for batch processing of data. Operations on arrays are carried out in bulk, which minimizes the overhead associated with function calls and memory allocation. This is especially beneficial when handling large datasets.

##5. Multithreading and Parallelism:

###Utilization of Low-Level Libraries:

NumPy often leverages highly optimized libraries like BLAS and LAPACK, which can utilize multithreading and optimized CPU instructions for array operations. This leads to substantial performance improvements for large-scale numerical tasks.

##6. Broadcasting:

Efficient Handling of Different Shapes: NumPy's broadcasting rules allow operations between arrays of different shapes without the need for manual replication of data. This makes it easier to perform calculations without the overhead of reshaping or repeating data.

#**7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

In NumPy, vstack() and hstack() are functions used to stack arrays along different axes. Here’s a comparison of the two, along with examples demonstrating their usage.

##np.vstack():

###Purpose:

Stacks arrays vertically (along rows).

###Usage:

Combines arrays by adding rows. The arrays must have the same number of columns.

#Example:

In [41]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

vstacked = np.vstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Vstacked Result:\n", vstacked)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Vstacked Result:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


##np.hstack():

###Purpose:

Stacks arrays horizontally (along columns).

###Usage:

Combines arrays by adding columns. The arrays must have the same number of rows.

#Example:

In [42]:
array3 = np.array([[1, 2],
                   [3, 4]])

array4 = np.array([[5, 6],
                   [7, 8]])

hstacked = np.hstack((array3, array4))

print("Array 3:\n", array3)
print("Array 4:\n", array4)
print("Hstacked Result:\n", hstacked)


Array 3:
 [[1 2]
 [3 4]]
Array 4:
 [[5 6]
 [7 8]]
Hstacked Result:
 [[1 2 5 6]
 [3 4 7 8]]


#**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**

In NumPy, the methods fliplr() and flipud() are used to flip arrays along different axes. Here’s a detailed explanation of their differences and effects on various array dimensions:

##np.fliplr():
###Purpose:

Flips an array left to right (horizontally).

###Effect:

It reverses the order of the columns in the input array.

#Example:

In [44]:
import numpy as np

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

flipped_lr = np.fliplr(array_2d)

print("Original 2D array:\n", array_2d)
print("Flipped Left to Right:\n", flipped_lr)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped Left to Right:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


##p.flipud():

###Purpose:

Flips an array up to down (vertically).

###Effect:

It reverses the order of the rows in the input array.

#Example:

In [45]:
flipped_ud = np.flipud(array_2d)

print("Original 2D array:\n", array_2d)
print("Flipped Up to Down:\n", flipped_ud)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped Up to Down:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


##Effects on Various Array Dimensions:

###1. 1D Arrays:

Both fliplr() and flipud() will have the same effect since they operate along dimensions that do not exist in a 1D array. For a 1D array, using either method will result in reversing the order of the elements.

In [46]:
array_1d = np.array([1, 2, 3, 4, 5])
print("Original 1D array:", array_1d)
print("Flipped 1D array (fliplr):", np.fliplr(array_1d.reshape(1, -1)))
print("Flipped 1D array (flipud):", np.flipud(array_1d.reshape(1, -1)))

Original 1D array: [1 2 3 4 5]
Flipped 1D array (fliplr): [[5 4 3 2 1]]
Flipped 1D array (flipud): [[1 2 3 4 5]]


###2. 2D Arrays:

fliplr() flips the columns of the 2D array, while flipud() flips the rows.

###3. Higher-Dimensional Arrays:

Both functions can still be applied to higher-dimensional arrays, but they will operate only on the last two dimensions. For example, if you have a 3D array, fliplr() will flip the last two dimensions (the last axis is considered the columns), and flipud() will flip the rows within the last two dimensions.

##Summary of Differences:

###Axis of Operation:

####fliplr():

Flips the array horizontally (reverses column order).
####flipud():

Flips the array vertically (reverses row order).

###Use Cases:

Use fliplr() when you need to reverse the arrangement of columns.
Use flipud() when you need to reverse the arrangement of rows.

#**9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**


The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It is particularly useful when you want to divide an array into smaller parts for processing or analysis.

##Functionality of array_split()

###1. Basic Syntax:

In [ ]:
numpy.array_split(ary, indices_or_sections, axis=0)

####ary:

The input array to be split.

####indices_or_sections:

This can be either an integer or a 1D array-like object:

* If it's an integer, it represents the number of equal parts to split the array into.

* If it's an array-like, it specifies the indices at which to split the array.

####axis:

The axis along which to split the array (default is 0).

###Return Value:

* Returns a list of sub-arrays. If the input array is not evenly divisible by the specified number of sections, the resulting sub-arrays will be as evenly sized as possible.

##Handling Uneven Splits:

When you use array_split() with an integer that does not divide the array evenly, NumPy ensures that the remaining elements are distributed as evenly as possible among the resulting sub-arrays.

* The first few sub-arrays will have one more element than the others if there are leftover elements.
#Examples:

#Example 1: Basic Usage

In [47]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7])

split_arrays = np.array_split(array, 3)

print("Original array:", array)
print("Split arrays:", split_arrays)

Original array: [1 2 3 4 5 6 7]
Split arrays: [array([1, 2, 3]), array([4, 5]), array([6, 7])]


In this case, the original array of size 7 is split into 3 sub-arrays. The first sub-array contains 3 elements, while the other two contain 2 elements each.

#Example 2: Uneven Splits in 2D Arrays

In [ ]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

split_2d = np.array_split(array_2d, 3)

print("Original 2D array:\n", array_2d)
print("Split 2D arrays:")
for i, arr in enumerate(split_2d):
    print(f"Array {i + 1}:\n", arr)

In this example, the 2D array is split into 3 parts along the first axis. The first sub-array contains 2 rows, while the second contains 1 row, and the third also contains 1 row, reflecting the uneven distribution.

#**10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

Vectorization and broadcasting are two powerful concepts in NumPy that contribute significantly to efficient array operations. Understanding these concepts is key to harnessing the full potential of NumPy for numerical computations.

#Vectorization:

Vectorization refers to the ability to perform operations on entire arrays (or large chunks of data) without the need for explicit loops. Instead of iterating over elements in Python, vectorized operations leverage optimized C and Fortran code under the hood, which greatly enhances performance.

##Benefits:

###Performance:

Vectorized operations are faster than traditional Python loops because they minimize the overhead associated with Python's interpreted nature. This leads to reduced execution time, especially for large datasets.

###Conciseness:

Code becomes more concise and readable. You can perform complex operations in a single line, which reduces the risk of errors and improves maintainability.

#Example:

In [49]:
import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

c = a + b

In this example, the addition of two large arrays is done in a single operation, which is much faster than adding the elements using a loop.

#Broadcasting:

Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes and sizes without explicitly resizing them. When operating on two arrays, NumPy automatically expands the smaller array across the larger array so that they have compatible shapes.

##Rules for Broadcasting:

If the arrays have a different number of dimensions, the shape of the smaller array is padded with ones on the left side until both shapes are the same.

If the size of the dimensions does not match, the size of one of the dimensions must be 1 for broadcasting to occur.
The result has the shape of the larger array.
Benefits:

###Flexibility:

Broadcasting allows for operations between arrays of different shapes without needing to create copies of the data, which saves memory.

###Efficiency:

It eliminates the need for explicit loops, thus improving performance and making the code cleaner.

#Example:

In [50]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

result = a + b

print("Array a:\n", a)
print("Array b:\n", b)
print("Result of broadcasting:\n", result)

Array a:
 [[1 2 3]
 [4 5 6]]
Array b:
 [10 20 30]
Result of broadcasting:
 [[11 22 33]
 [14 25 36]]


In this example, the 1D array b is broadcasted across the rows of the 2D array a, allowing for element-wise addition without needing to manually expand b.

#**PRACTICAL QUESTIONS:**

#**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [51]:
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))

print("Original Array:\n", array)

transposed_array = array.T

print("Transposed Array:\n", transposed_array)

Original Array:
 [[20 13 78]
 [35 24 42]
 [97 16 78]]
Transposed Array:
 [[20 35 97]
 [13 24 16]
 [78 42 78]]


#**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [52]:
import numpy as np

array_1d = np.arange(10)

print("Original 1D Array:\n", array_1d)

array_2x5 = array_1d.reshape(2, 5)
print("Reshaped into 2x5 Array:\n", array_2x5)

array_5x2 = array_1d.reshape(5, 2)
print("Reshaped into 5x2 Array:\n", array_5x2)

Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped into 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped into 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [53]:
import numpy as np

array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:\n", array_4x4)

array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("6x6 Array with Border of Zeros:\n", array_with_border)

Original 4x4 Array:
 [[0.23583406 0.17057977 0.43650275 0.59861694]
 [0.13231654 0.84501162 0.53670729 0.68388911]
 [0.06568968 0.96580938 0.91758832 0.49238424]
 [0.7531135  0.40526347 0.43963258 0.03803389]]
6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.23583406 0.17057977 0.43650275 0.59861694 0.        ]
 [0.         0.13231654 0.84501162 0.53670729 0.68388911 0.        ]
 [0.         0.06568968 0.96580938 0.91758832 0.49238424 0.        ]
 [0.         0.7531135  0.40526347 0.43963258 0.03803389 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [54]:
import numpy as np

array = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:\n", array)

Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


#**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**

In [55]:
import numpy as np

array_strings = np.array(['python', 'numpy', 'pandas'])

uppercase_array = np.char.upper(array_strings)
lowercase_array = np.char.lower(array_strings)
titlecase_array = np.char.title(array_strings)
capitalize_array = np.char.capitalize(array_strings)

print("Original Array:\n", array_strings)
print("Uppercase:\n", uppercase_array)
print("Lowercase:\n", lowercase_array)
print("Title Case:\n", titlecase_array)
print("Capitalized:\n", capitalize_array)

Original Array:
 ['python' 'numpy' 'pandas']
Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Title Case:
 ['Python' 'Numpy' 'Pandas']
Capitalized:
 ['Python' 'Numpy' 'Pandas']


#**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [56]:
import numpy as np

array_words = np.array(['hello', 'numpy', 'python', 'data'])

spaced_array = np.char.join(' ', array_words)

print("Original Array:\n", array_words)
print("Array with Spaces:\n", spaced_array)

Original Array:
 ['hello' 'numpy' 'python' 'data']
Array with Spaces:
 ['h e l l o' 'n u m p y' 'p y t h o n' 'd a t a']


#**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [57]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[10, 20, 30],
                   [40, 50, 60]])

addition = array1 + array2

subtraction = array1 - array2

multiplication = array1 * array2

division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[10 20 30]
 [40 50 60]]
Element-wise Addition:
 [[11 22 33]
 [44 55 66]]
Element-wise Subtraction:
 [[ -9 -18 -27]
 [-36 -45 -54]]
Element-wise Multiplication:
 [[ 10  40  90]
 [160 250 360]]
Element-wise Division:
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


#**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [58]:
import numpy as np

identity_matrix = np.eye(5)

print("5x5 Identity Matrix:\n", identity_matrix)

diagonal_elements = identity_matrix.diagonal()

print("Diagonal Elements:\n", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


#**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**



In [62]:
import numpy as np

random_integers = np.random.randint(0, 1001, size=100)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = np.array([num for num in random_integers if is_prime(num)])

print("Random Integers Array:\n", random_integers)
print("Prime Numbers in the Array:\n", prime_numbers)

Random Integers Array:
 [833 773 449 424 169 719 741 516  92 200 444 807  53 163 786 840 667 458
 459 997 229 295 435  59 927 308 281 796 979 584  93 930 844  89 133 388
 374 728 640 928 928 128 103 930 264 309 923 354 257 655 292 203 627 799
 653 315 250 489 306 758 452 538 103 945 760 117 482 556 882 548 275 448
 700  15 332 224 992  75 435 415 384 758 307 192 143 293 922 141  16 310
 705 835 601 604 645  45 766 306 768 324]
Prime Numbers in the Array:
 [773 449 719  53 163 997 229  59 281  89 103 257 653 103 307 293 601]


#**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**

In [66]:
import numpy as np

daily_temperatures = np.random.normal(loc=20, scale=5, size=30)

daily_temperatures = np.clip(daily_temperatures, 0, 35)

print("Daily Temperatures for the Month:\n", daily_temperatures)

weekly_averages = []

for i in range(0, 30, 7):
    week = daily_temperatures[i:i + 7]
    weekly_avg = np.mean(week)
    weekly_averages.append(weekly_avg)

print("Weekly Averages:\n", weekly_averages)

Daily Temperatures for the Month:
 [12.31509357 14.31347778 15.44771488 24.70418531 15.0004056  25.45849317
 18.12589678 23.8341431  22.53823446 18.14453304 18.77387467 20.99960132
 16.17527937  5.61763461 20.20133838 17.08915486 17.65006803 15.43721775
 16.44742541 27.01404489 27.17152812 14.50133896 13.3713406  20.52501815
 13.48088943 20.55235455 21.84152555 20.36450161 25.19380178 23.2762914 ]
Weekly Averages:
 [17.909323869904448, 18.01190008283944, 20.14439677702146, 17.805281264245306, 24.235046591969795]
